apiVersion: v1
kind: Service
metadata:
  name: tera2-service
  labels:
    app: tera2-service
spec:
  type: NodePort
  ports:
  - port: 25777
    targetPort: 25777
    nodePort: 31102
    protocol: TCP
    name: tera2-port
  selector:
    app: tera2
